// Copyright (c) Jake Helfert
// Licensed under the MIT License.
//
// The windows-1252 <-> Unicode mapping, loaded from the cp1252 item in
// codepages.dat (via ICU's udata layer).
//
// cp1252 is the only non-Unicode code page ESE text columns use
// (usEnglishCodePage); the other, 1200, is native UTF-16 and needs no table.
// The table is generated byte-for-byte by NlsDataGenerator and read here
// rather than hard-coded, so it has a single source of truth.

#pragma once

#include <stdint.h>

#include <unordered_map>

class CodePageTable
{
public:
    // The shared windows-1252 table, loaded on first use from the cp1252 item.
    // Returns nullptr if the item is missing or malformed.
    static const CodePageTable* Instance();

    // The Unicode scalar for a 1252 byte. Every byte maps to a BMP scalar
    // (undefined 1252 positions map to the C1 control of the same value).
    uint16_t ToUnicode(unsigned char byte) const;

    // The 1252 byte encoding a Unicode scalar, or -1 if not representable.
    int FromUnicode(uint32_t scalar) const;

private:
    bool Load();

    static constexpr uint32_t EntryCount = 256;

    uint16_t _toUnicode[EntryCount];
    std::unordered_map<uint16_t, uint8_t> _fromUnicode;
};
